name: Build, Test And Publish Docker To DockerHub

on: 
  push:
    branches:
      - main
      
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Check Out Repository
        uses: actions/checkout@v1

      - name: Node
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
 
      - name: Install dependencies
        run: npm install --force
 
      - name: Run tests
        run: npm test
 
      - name: Build
        run: npm run build
        # Ignore non-zero exit code (warnings won't cause the build to fail)
        continue-on-error: true


      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Build
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          # build image in pull requests
          # publish only if branch is `main`
          push: ${{ github.ref == 'refs/heads/main'}}
          # define at which tag should be docker image published
          tags: maja669e/wineshopfrontendservice:latest
          # path to Dockerfile
          file: ./Dockerfile
